name: emotion_recognition_app
description: App de reconocimiento de emociones con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4

  # HTTP
  http: ^1.1.0

  # Conversión de imágenes
  image: ^4.1.3

  # State Management
  provider: ^6.1.1

  # Permisos
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true